### ISSUE TITLE
What is your setup for those crystal clear gifs?

### ISSUE THREAD

**Issue by aserowy** [Pocco81/AutoSave.nvim#2]
Heho,

saw your plugin and im jealous :D, my videos for [tmux.nvim](https://github.com/aserowy/tmux.nvim) are washed and mp4.. how did you created this clear and sharp gif preview?

Kind regards

Alexander

**Comment by Pocco81** [comment]
Oh well, I always use [Peek](https://github.com/phw/peek) for recording the .gifs, and my current config is to record at a high frame rate (e.g. 30fps) without recording the whole screen, nor a 10 x 10 pxl space.

If it's big it'll look out of focus and if it is two small the high frame rate becomes useless. That's why I usually do a forth of my screen (laptop) and increase the font size.

Also get a wallpaper to contrast the terminal property. As you can see mine is pink and white, and my terminal has a  gray-blue tone.

**Comment by Pocco81** [comment]
Btw nice plug-in! Out of topic but... I've never gotten into Tmux. But I'd really like to in order to have a consistent workflow regardless of which terminal I'm using.

Any recommendations for where to start?

**Comment by aserowy** [comment]
ty for the heads up! I think the start should be to translate your current in nvim workflow to tmux. (That was the way i dipped into tmux.) At first i started with window movement and resizing. Later came plugins like automated session management and session "movement". At last the whole clipboard and keyboard only movement of terminal histories.

The transition was easy compared to my journey with vim/nvim. Progress is easy to force. Took me one Weekend to get started and round about one week to get settled :D 

Biggest pain point was to find good bindings, because the defaults are bull $%^& :)
The second was the distribution of different versions on different nixs. Thus, i forced myself to enable a stable environment by learning nix pkgs and home manager. Now its a breeze to initialize my work flow everywhere from windows (with wsl) to *nix. One flow.

Learned alot on the way and i am not looking back!

**Comment by aserowy** [comment]
Here is my current [config](https://github.com/aserowy/dots/blob/main/programs/tmux.nix). I think it is best, to just set useful bindings first. Start small and add more and more the better you get.
